// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xinle.proto

package com.xinle.protolearn;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xinle.protolearn.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.xinle.protolearn.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<com.xinle.protolearn.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .com.xinle.protolearn.StudentResponse studentResponse = 1;</code>
   */
  com.xinle.protolearn.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .com.xinle.protolearn.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .com.xinle.protolearn.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends com.xinle.protolearn.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .com.xinle.protolearn.StudentResponse studentResponse = 1;</code>
   */
  com.xinle.protolearn.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
