// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xinle.proto

package com.xinle.protolearn;

public interface StudentAgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xinle.protolearn.StudentAge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
